import type { FacetCode, Factor } from "./scoring120";

export interface Item120 {
  id: number;
  th: string;
  en: string;
  facet: FacetCode;
  facetName: string;
  factor: Factor;
  reverse: boolean;
}

export const items120: Item120[] = [
  // ── N1: Anxiety ──────────────────────────────────────────
  {
    id: 1,
    th: "มักกังวลเรื่องต่างๆ",
    en: "Worry about things.",
    facet: "N1",
    facetName: "Anxiety",
    factor: "N",
    reverse: false,
  },
  {
    id: 31,
    th: "ไม่ค่อยเก็บเรื่องต่างๆ มาว้าวุ่นใจ",
    en: "Am not easily bothered by things.",
    facet: "N1",
    facetName: "Anxiety",
    factor: "N",
    reverse: true,
  },
  {
    id: 61,
    th: "มักจะคิดในแง่ร้ายหรือแย่ที่สุดไว้ก่อนเสมอ",
    en: "Fear for the worst.",
    facet: "N1",
    facetName: "Anxiety",
    factor: "N",
    reverse: false,
  },
  {
    id: 91,
    th: "มีความหวาดกลัวต่อหลายสิ่งหลายอย่าง",
    en: "Am afraid of many things.",
    facet: "N1",
    facetName: "Anxiety",
    factor: "N",
    reverse: false,
  },

  // ── N2: Anger ─────────────────────────────────────────────
  {
    id: 2,
    th: "โกรธง่าย",
    en: "Get angry easily.",
    facet: "N2",
    facetName: "Anger",
    factor: "N",
    reverse: false,
  },
  {
    id: 32,
    th: "ไม่ค่อยหงุดหงิดอะไรง่ายๆ",
    en: "Rarely get irritated.",
    facet: "N2",
    facetName: "Anger",
    factor: "N",
    reverse: true,
  },
  {
    id: 62,
    th: "อารมณ์เสียได้ง่าย",
    en: "Get upset easily.",
    facet: "N2",
    facetName: "Anger",
    factor: "N",
    reverse: false,
  },
  {
    id: 92,
    th: "มักจะมีความระแวงสงสัยในหลายๆ เรื่อง",
    en: "Am filled with doubts about things.",
    facet: "N2",
    facetName: "Anger",
    factor: "N",
    reverse: false,
  },

  // ── N3: Depression ────────────────────────────────────────
  {
    id: 3,
    th: "มักจะรู้สึกเศร้าซึม",
    en: "Often feel blue.",
    facet: "N3",
    facetName: "Depression",
    factor: "N",
    reverse: false,
  },
  {
    id: 33,
    th: "รู้สึกพอใจในตัวเอง",
    en: "Feel comfortable with myself.",
    facet: "N3",
    facetName: "Depression",
    factor: "N",
    reverse: true,
  },
  {
    id: 63,
    th: "ไม่ชอบตัวเอง",
    en: "Dislike myself.",
    facet: "N3",
    facetName: "Depression",
    factor: "N",
    reverse: false,
  },
  {
    id: 93,
    th: "อารมณ์แปรปรวนขึ้นลงบ่อย",
    en: "Have frequent mood swings.",
    facet: "N3",
    facetName: "Depression",
    factor: "N",
    reverse: false,
  },

  // ── N4: Self-Consciousness ────────────────────────────────
  {
    id: 4,
    th: "รู้สึกเขินอายง่าย ขี้อาย",
    en: "Am easily embarrassed.",
    facet: "N4",
    facetName: "Self-Consciousness",
    factor: "N",
    reverse: false,
  },
  {
    id: 34,
    th: "ไม่อายอะไรง่ายๆ เป็นคนเปิดเผย",
    en: "Am not embarrassed easily.",
    facet: "N4",
    facetName: "Self-Consciousness",
    factor: "N",
    reverse: true,
  },
  {
    id: 64,
    th: "รู้สึกว่าการเข้าหาผู้อื่นเป็นเรื่องยาก",
    en: "Find it difficult to approach others.",
    facet: "N4",
    facetName: "Self-Consciousness",
    factor: "N",
    reverse: false,
  },
  {
    id: 94,
    th: "มักกลัวว่าจะทำอะไรผิดพลาด",
    en: "Am afraid that I will do the wrong thing.",
    facet: "N4",
    facetName: "Self-Consciousness",
    factor: "N",
    reverse: false,
  },

  // ── N5: Immoderation ──────────────────────────────────────
  {
    id: 5,
    th: "ทนต่อความอยากของตนเองไม่ค่อยได้",
    en: "Find it difficult to resist my cravings.",
    facet: "N5",
    facetName: "Immoderation",
    factor: "N",
    reverse: false,
  },
  {
    id: 35,
    th: "สามารถต้านทานสิ่งเย้ายวนต่างๆ ได้ง่ายมาก",
    en: "Easily resist temptations.",
    facet: "N5",
    facetName: "Immoderation",
    factor: "N",
    reverse: true,
  },
  {
    id: 65,
    th: "รักการกิน",
    en: "Love to eat.",
    facet: "N5",
    facetName: "Immoderation",
    factor: "N",
    reverse: false,
  },
  {
    id: 95,
    th: "มีปัญหาในการคุมตัวเอง ต่ออารมณ์ที่เกิดขึ้น",
    en: "Have trouble resisting my urges.",
    facet: "N5",
    facetName: "Immoderation",
    factor: "N",
    reverse: false,
  },

  // ── N6: Vulnerability ─────────────────────────────────────
  {
    id: 6,
    th: "ตื่นตระหนก ขี้ตกใจง่าย",
    en: "Panic easily.",
    facet: "N6",
    facetName: "Vulnerability",
    factor: "N",
    reverse: false,
  },
  {
    id: 36,
    th: "สงบสติอารมณ์ได้ภายใต้ความกดดัน",
    en: "Remain calm under pressure.",
    facet: "N6",
    facetName: "Vulnerability",
    factor: "N",
    reverse: true,
  },
  {
    id: 66,
    th: "รับไม่ไหวถ้าสถานการณ์ต่างๆถาโถมเข้ามา",
    en: "Become overwhelmed by events.",
    facet: "N6",
    facetName: "Vulnerability",
    factor: "N",
    reverse: false,
  },
  {
    id: 96,
    th: "รู้สึกว่าตนเองไม่สามารถจัดการกับเรื่องต่างๆได้",
    en: "Feel that I'm unable to deal with things.",
    facet: "N6",
    facetName: "Vulnerability",
    factor: "N",
    reverse: false,
  },

  // ── E1: Friendliness ──────────────────────────────────────
  {
    id: 7,
    th: "ผูกมิตรกับคนอื่นได้ง่าย",
    en: "Make friends easily.",
    facet: "E1",
    facetName: "Friendliness",
    factor: "E",
    reverse: false,
  },
  {
    id: 37,
    th: "รักษาระยะห่างกับผู้อื่นเสมอ",
    en: "Keep others at a distance.",
    facet: "E1",
    facetName: "Friendliness",
    factor: "E",
    reverse: true,
  },
  {
    id: 67,
    th: "ทำความคุ้นเคยกับคนอื่นได้อย่างรวดเร็ว",
    en: "Warm up quickly to others.",
    facet: "E1",
    facetName: "Friendliness",
    factor: "E",
    reverse: false,
  },
  {
    id: 97,
    th: "รู้สึกสบายใจเมื่ออยู่ท่ามกลางผู้คน",
    en: "Feel comfortable around people.",
    facet: "E1",
    facetName: "Friendliness",
    factor: "E",
    reverse: false,
  },

  // ── E2: Gregariousness ────────────────────────────────────
  {
    id: 8,
    th: "ชอบงานเลี้ยงใหญ่ๆ",
    en: "Love large parties.",
    facet: "E2",
    facetName: "Gregariousness",
    factor: "E",
    reverse: false,
  },
  {
    id: 38,
    th: "หลีกเลี่ยงสถานที่ที่มีคนพลุกพล่าน",
    en: "Avoid crowds.",
    facet: "E2",
    facetName: "Gregariousness",
    factor: "E",
    reverse: true,
  },
  {
    id: 68,
    th: "ได้พูดคุยกับผู้คนมากมายเวลาไปงานสังสรรค์",
    en: "Talk to a lot of different people at parties.",
    facet: "E2",
    facetName: "Gregariousness",
    factor: "E",
    reverse: false,
  },
  {
    id: 98,
    th: "ชอบอยู่คนเดียวมากกว่า",
    en: "Prefer to be alone.",
    facet: "E2",
    facetName: "Gregariousness",
    factor: "E",
    reverse: true,
  },

  // ── E3: Assertiveness ─────────────────────────────────────
  {
    id: 9,
    th: "ชอบเป็นผู้นำและผู้จัดการ",
    en: "Take charge.",
    facet: "E3",
    facetName: "Assertiveness",
    factor: "E",
    reverse: false,
  },
  {
    id: 39,
    th: "รอให้คนอื่นเป็นคนนำก่อนเสมอ",
    en: "Wait for others to lead the way.",
    facet: "E3",
    facetName: "Assertiveness",
    factor: "E",
    reverse: true,
  },
  {
    id: 69,
    th: "กล้าพูดและพิสูจน์จุดยืนของตนเอง",
    en: "Speak up for myself.",
    facet: "E3",
    facetName: "Assertiveness",
    factor: "E",
    reverse: false,
  },
  {
    id: 99,
    th: "ไม่ใช่คนที่พร้อมจะแสดงออกเท่าไหร่",
    en: "Am not very assertive.",
    facet: "E3",
    facetName: "Assertiveness",
    factor: "E",
    reverse: true,
  },

  // ── E4: Activity Level ────────────────────────────────────
  {
    id: 10,
    th: "ยุ่งอยู่ตลอดเวลา",
    en: "Am always busy.",
    facet: "E4",
    facetName: "Activity Level",
    factor: "E",
    reverse: false,
  },
  {
    id: 40,
    th: "ชอบทำตัวสบายๆง่ายๆเสมอ",
    en: "Like to take it easy.",
    facet: "E4",
    facetName: "Activity Level",
    factor: "E",
    reverse: true,
  },
  {
    id: 70,
    th: "เดินทางหรือทำกิจกรรมอยู่ตลอด",
    en: "Am always on the go.",
    facet: "E4",
    facetName: "Activity Level",
    factor: "E",
    reverse: false,
  },
  {
    id: 100,
    th: "มักหาอะไรทำถ้ามีเวลาว่าง",
    en: "Do a lot in my spare time.",
    facet: "E4",
    facetName: "Activity Level",
    factor: "E",
    reverse: false,
  },

  // ── E5: Excitement-Seeking ────────────────────────────────
  {
    id: 11,
    th: "ชอบความตื่นเต้นเร้าใจ",
    en: "Love excitement.",
    facet: "E5",
    facetName: "Excitement-Seeking",
    factor: "E",
    reverse: false,
  },
  {
    id: 41,
    th: "ไม่ชอบเพลงเสียงดัง",
    en: "Dislike loud music.",
    facet: "E5",
    facetName: "Excitement-Seeking",
    factor: "E",
    reverse: true,
  },
  {
    id: 71,
    th: "แสวงหาการผจญภัยและท่องเที่ยว",
    en: "Seek adventure.",
    facet: "E5",
    facetName: "Excitement-Seeking",
    factor: "E",
    reverse: false,
  },
  {
    id: 101,
    th: "สนุกที่ได้เป็นส่วนหนึ่งของฝูงชนที่ส่งเสียงดัง",
    en: "Enjoy being part of a loud crowd.",
    facet: "E5",
    facetName: "Excitement-Seeking",
    factor: "E",
    reverse: false,
  },

  // ── E6: Cheerfulness ──────────────────────────────────────
  {
    id: 12,
    th: "เป็นคนร่าเริงและเปล่งประกายความสุข",
    en: "Radiate joy.",
    facet: "E6",
    facetName: "Cheerfulness",
    factor: "E",
    reverse: false,
  },
  {
    id: 42,
    th: "ยากที่มีอะไรจะทำให้ฉันรู้สึกตลกหรือขำ",
    en: "Am not easily amused.",
    facet: "E6",
    facetName: "Cheerfulness",
    factor: "E",
    reverse: true,
  },
  {
    id: 72,
    th: "สนุกสนานเฮฮาอยู่เสมอ",
    en: "Have a lot of fun.",
    facet: "E6",
    facetName: "Cheerfulness",
    factor: "E",
    reverse: false,
  },
  {
    id: 102,
    th: "แสดงความสุขออกมาได้ง่ายๆเหมือนเด็กๆ",
    en: "Express childlike joy.",
    facet: "E6",
    facetName: "Cheerfulness",
    factor: "E",
    reverse: false,
  },

  // ── O1: Imagination ───────────────────────────────────────
  {
    id: 13,
    th: "มีจินตนาการโลดแล่นและมีชีวิตชีวา",
    en: "Have a vivid imagination.",
    facet: "O1",
    facetName: "Imagination",
    factor: "O",
    reverse: false,
  },
  {
    id: 43,
    th: "ไม่ค่อยชอบฝันกลางวัน",
    en: "Seldom daydream.",
    facet: "O1",
    facetName: "Imagination",
    factor: "O",
    reverse: true,
  },
  {
    id: 73,
    th: "ชอบที่จะฝันกลางวันอยู่บ่อยๆ",
    en: "Love to daydream.",
    facet: "O1",
    facetName: "Imagination",
    factor: "O",
    reverse: false,
  },
  {
    id: 103,
    th: "สนุกไปกับความคิดเพ้อฝันที่หลุดโลก",
    en: "Enjoy wild flights of fantasy.",
    facet: "O1",
    facetName: "Imagination",
    factor: "O",
    reverse: false,
  },

  // ── O2: Artistic Interests ────────────────────────────────
  {
    id: 14,
    th: "เชื่อในความสำคัญของศิลปะ",
    en: "Believe in the importance of art.",
    facet: "O2",
    facetName: "Artistic Interests",
    factor: "O",
    reverse: false,
  },
  {
    id: 44,
    th: "ไม่ค่อยสนใจศิลปะ",
    en: "Do not like art.",
    facet: "O2",
    facetName: "Artistic Interests",
    factor: "O",
    reverse: true,
  },
  {
    id: 74,
    th: "เห็นความสวยงามในสิ่งที่คนอื่นมักมองข้าม",
    en: "See beauty in things that others might not notice.",
    facet: "O2",
    facetName: "Artistic Interests",
    factor: "O",
    reverse: false,
  },
  {
    id: 104,
    th: "ชอบอ่านเนื้อหาที่ท้าทายความคิด",
    en: "Love to read challenging material.",
    facet: "O2",
    facetName: "Artistic Interests",
    factor: "O",
    reverse: false,
  },

  // ── O3: Emotionality ──────────────────────────────────────
  {
    id: 15,
    th: "สัมผัสอารมณ์ความรู้สึกของตนเองได้อย่างลึกซึ้ง",
    en: "Experience my emotions intensely.",
    facet: "O3",
    facetName: "Emotionality",
    factor: "O",
    reverse: false,
  },
  {
    id: 45,
    th: "ไม่เข้าใจคนที่ใช้อารมณ์เยอะ",
    en: "Don't understand people who get emotional.",
    facet: "O3",
    facetName: "Emotionality",
    factor: "O",
    reverse: true,
  },
  {
    id: 75,
    th: "หลงใหลและมีอารมณ์ร่วมไปกับอุดมการณ์ต่างๆ",
    en: "Am passionate about causes.",
    facet: "O3",
    facetName: "Emotionality",
    factor: "O",
    reverse: false,
  },
  {
    id: 105,
    th: "รับรู้และรู้สึกถึงอารมณ์ของผู้อื่นได้",
    en: "Feel others' emotions.",
    facet: "O3",
    facetName: "Emotionality",
    factor: "O",
    reverse: false,
  },

  // ── O4: Adventurousness ───────────────────────────────────
  {
    id: 16,
    th: "ชอบความหลากหลายมากกว่ากิจวัตรจำเจ",
    en: "Prefer variety to routine.",
    facet: "O4",
    facetName: "Adventurousness",
    factor: "O",
    reverse: false,
  },
  {
    id: 46,
    th: "ชอบยึดติดกับสิ่งที่ตัวเองคุ้นเคยอยู่แล้ว",
    en: "Prefer to stick with things that I know.",
    facet: "O4",
    facetName: "Adventurousness",
    factor: "O",
    reverse: true,
  },
  {
    id: 76,
    th: "ชอบไปเที่ยวชมสถานที่ใหม่ๆ",
    en: "Like to visit new places.",
    facet: "O4",
    facetName: "Adventurousness",
    factor: "O",
    reverse: false,
  },
  {
    id: 106,
    th: "มีความสนใจในเรื่องต่างๆ มากมาย",
    en: "Am interested in many things.",
    facet: "O4",
    facetName: "Adventurousness",
    factor: "O",
    reverse: false,
  },

  // ── O5: Intellect ─────────────────────────────────────────
  {
    id: 17,
    th: "ชอบคิดหาวิธีใหม่ๆ ในการทำสิ่งต่างๆ",
    en: "Love to think up new ways of doing things.",
    facet: "O5",
    facetName: "Intellect",
    factor: "O",
    reverse: false,
  },
  {
    id: 47,
    th: "หลีกเลี่ยงการถกเถียงเชิงปรัชญา",
    en: "Avoid philosophical discussions.",
    facet: "O5",
    facetName: "Intellect",
    factor: "O",
    reverse: true,
  },
  {
    id: 77,
    th: "สนุกกับการคิดทบทวนเรื่องต่างๆ",
    en: "Enjoy thinking about things.",
    facet: "O5",
    facetName: "Intellect",
    factor: "O",
    reverse: false,
  },
  {
    id: 107,
    th: "มีคลังคำศัพท์ที่หลากหลายและมากมาย",
    en: "Have a rich vocabulary.",
    facet: "O5",
    facetName: "Intellect",
    factor: "O",
    reverse: false,
  },

  // ── O6: Liberalism ────────────────────────────────────────
  {
    id: 18,
    th: "มีแนวโน้มที่จะสนับสนุนนักการเมืองที่หัวก้าวหน้า",
    en: "Tend to vote for liberal political candidates.",
    facet: "O6",
    facetName: "Liberalism",
    factor: "O",
    reverse: false,
  },
  {
    id: 48,
    th: "มีแนวโน้มที่จะสนับสนุนนักการเมืองที่หัวอนุรักษ์",
    en: "Tend to vote for conservative political candidates.",
    facet: "O6",
    facetName: "Liberalism",
    factor: "O",
    reverse: true,
  },
  {
    id: 78,
    th: "เชื่อว่าความถูกหรือผิดนั้นไม่มีอยู่จริงแบบร้อยเปอร์เซ็นต์",
    en: "Believe that there is no absolute right or wrong.",
    facet: "O6",
    facetName: "Liberalism",
    factor: "O",
    reverse: false,
  },
  {
    id: 108,
    th: "รู้สึกว่ากฎหมายควรบังคับใช้อย่างเข้มงวด",
    en: "Feel that laws should be strictly enforced.",
    facet: "O6",
    facetName: "Liberalism",
    factor: "O",
    reverse: true,
  },

  // ── A1: Trust ─────────────────────────────────────────────
  {
    id: 19,
    th: "ไว้ใจผู้อื่นง่ายๆ",
    en: "Trust others.",
    facet: "A1",
    facetName: "Trust",
    factor: "A",
    reverse: false,
  },
  {
    id: 49,
    th: "มักสงสัยว่าผู้อื่นมีเจตนาแอบแฝง",
    en: "Suspect hidden motives in others.",
    facet: "A1",
    facetName: "Trust",
    factor: "A",
    reverse: true,
  },
  {
    id: 79,
    th: "เชื่อว่าผู้อื่นมีเจตนาที่ดี",
    en: "Believe that others have good intentions.",
    facet: "A1",
    facetName: "Trust",
    factor: "A",
    reverse: false,
  },
  {
    id: 109,
    th: "คอยระมัดระวังและหวาดระแวงผู้อื่นเสมอ",
    en: "Am wary of others.",
    facet: "A1",
    facetName: "Trust",
    factor: "A",
    reverse: true,
  },

  // ── A2: Morality ──────────────────────────────────────────
  {
    id: 20,
    th: "ใช้ผู้อื่นเพื่อผลประโยชน์ของตนได้",
    en: "Use others for my own ends.",
    facet: "A2",
    facetName: "Morality",
    factor: "A",
    reverse: true,
  },
  {
    id: 50,
    th: "พร้อมจะโกงเล็กน้อยเพื่อความก้าวหน้า",
    en: "Cheat to get ahead.",
    facet: "A2",
    facetName: "Morality",
    factor: "A",
    reverse: true,
  },
  {
    id: 80,
    th: "ควรใส่หน้ากากเพื่อให้คนอื่นนับถือ",
    en: "Pretend to be more than I am.",
    facet: "A2",
    facetName: "Morality",
    factor: "A",
    reverse: true,
  },
  {
    id: 110,
    th: "ต้องชิงความได้เปรียบก่อนผู้อื่น",
    en: "Take advantage of others.",
    facet: "A2",
    facetName: "Morality",
    factor: "A",
    reverse: true,
  },

  // ── A3: Altruism ──────────────────────────────────────────
  {
    id: 21,
    th: "ทำให้ผู้อื่นรู้สึกว่าได้รับการต้อนรับเสมอ",
    en: "Make people feel welcome.",
    facet: "A3",
    facetName: "Altruism",
    factor: "A",
    reverse: false,
  },
  {
    id: 51,
    th: "เฉยเมยต่อความรู้สึกของผู้อื่น",
    en: "Am indifferent to the feelings of others.",
    facet: "A3",
    facetName: "Altruism",
    factor: "A",
    reverse: true,
  },
  {
    id: 81,
    th: "คิดเผื่อความต้องการของผู้อื่นล่วงหน้า",
    en: "Anticipate the needs of others.",
    facet: "A3",
    facetName: "Altruism",
    factor: "A",
    reverse: false,
  },
  {
    id: 111,
    th: "รักที่จะช่วยเหลือผู้อื่น",
    en: "Love to help others.",
    facet: "A3",
    facetName: "Altruism",
    factor: "A",
    reverse: false,
  },

  // ── A4: Cooperation ───────────────────────────────────────
  {
    id: 22,
    th: "ทนไม่ได้กับการเผชิญหน้ากัน",
    en: "Can't stand confrontation.",
    facet: "A4",
    facetName: "Cooperation",
    factor: "A",
    reverse: false,
  },
  {
    id: 52,
    th: "ชอบการปะทะหรือถกเถียงอย่างมาก",
    en: "Love a good fight.",
    facet: "A4",
    facetName: "Cooperation",
    factor: "A",
    reverse: true,
  },
  {
    id: 82,
    th: "เกลียดที่จะทำตัวเป็นคนน่ารำคาญ",
    en: "Hate to seem pushy.",
    facet: "A4",
    facetName: "Cooperation",
    factor: "A",
    reverse: false,
  },
  {
    id: 112,
    th: "เป็นคนทำให้พอใจได้ง่ายมาก",
    en: "Am easy to satisfy.",
    facet: "A4",
    facetName: "Cooperation",
    factor: "A",
    reverse: false,
  },

  // ── A5: Modesty ───────────────────────────────────────────
  {
    id: 23,
    th: "ไม่ชอบตกเป็นจุดสนใจ",
    en: "Dislike being the center of attention.",
    facet: "A5",
    facetName: "Modesty",
    factor: "A",
    reverse: false,
  },
  {
    id: 53,
    th: "คิดว่าตัวเองเป็นคนสำคัญ",
    en: "Think highly of myself.",
    facet: "A5",
    facetName: "Modesty",
    factor: "A",
    reverse: true,
  },
  {
    id: 83,
    th: "ชอบอวดความสามารถและส่วนดีของตัวเอง",
    en: "Boast about my virtues.",
    facet: "A5",
    facetName: "Modesty",
    factor: "A",
    reverse: true,
  },
  {
    id: 113,
    th: "ประเมินตัวเองไว้สูง",
    en: "Have a high opinion of myself.",
    facet: "A5",
    facetName: "Modesty",
    factor: "A",
    reverse: true,
  },

  // ── A6: Sympathy ──────────────────────────────────────────
  {
    id: 24,
    th: "เห็นใจคนเร่ร่อนหรือไร้บ้าน",
    en: "Sympathize with the homeless.",
    facet: "A6",
    facetName: "Sympathy",
    factor: "A",
    reverse: false,
  },
  {
    id: 54,
    th: "ไม่สนใจปัญหาของผู้อื่น",
    en: "Am not interested in other people's problems.",
    facet: "A6",
    facetName: "Sympathy",
    factor: "A",
    reverse: true,
  },
  {
    id: 84,
    th: "รู้สึกสงสารผู้ที่ด้อยกว่าตนเองเสมอ",
    en: "Feel sympathy for those who are worse off than myself.",
    facet: "A6",
    facetName: "Sympathy",
    factor: "A",
    reverse: false,
  },
  {
    id: 114,
    th: "ให้คุณค่ากับความร่วมมือมากกว่าการแข่งขัน",
    en: "Value cooperation over competition.",
    facet: "A6",
    facetName: "Sympathy",
    factor: "A",
    reverse: false,
  },

  // ── C1: Self-Efficacy ─────────────────────────────────────
  {
    id: 25,
    th: "ทำงานต่างๆ จนสำเร็จลุล่วงด้วยดี",
    en: "Complete tasks successfully.",
    facet: "C1",
    facetName: "Self-Efficacy",
    factor: "C",
    reverse: false,
  },
  {
    id: 55,
    th: "มักจะลืมเก็บของให้เข้าที่",
    en: "Often forget to put things back in their proper place.",
    facet: "C1",
    facetName: "Self-Efficacy",
    factor: "C",
    reverse: true,
  },
  {
    id: 85,
    th: "คิดหาทางออกที่ดีให้กับปัญหาได้เสมอ",
    en: "Come up with good solutions.",
    facet: "C1",
    facetName: "Self-Efficacy",
    factor: "C",
    reverse: false,
  },
  {
    id: 115,
    th: "รู้ว่าต้องทำอย่างไรถึงจะจัดการสิ่งต่างๆ ได้สำเร็จ",
    en: "Know how to get things done.",
    facet: "C1",
    facetName: "Self-Efficacy",
    factor: "C",
    reverse: false,
  },

  // ── C2: Orderliness ───────────────────────────────────────
  {
    id: 26,
    th: "ชอบความเป็นระเบียบเรียบร้อย",
    en: "Like order.",
    facet: "C2",
    facetName: "Orderliness",
    factor: "C",
    reverse: false,
  },
  {
    id: 56,
    th: "ทิ้งความรกไว้ในห้องตนเอง",
    en: "Leave a mess in my room.",
    facet: "C2",
    facetName: "Orderliness",
    factor: "C",
    reverse: true,
  },
  {
    id: 86,
    th: "เก็บของให้เป็นระเบียบอยู่เสมอ",
    en: "Keep things tidy.",
    facet: "C2",
    facetName: "Orderliness",
    factor: "C",
    reverse: false,
  },
  {
    id: 116,
    th: "ขี้ลืมบ่อยครั้ง",
    en: "Often forget things.",
    facet: "C2",
    facetName: "Orderliness",
    factor: "C",
    reverse: true,
  },

  // ── C3: Dutifulness ───────────────────────────────────────
  {
    id: 27,
    th: "รักษาสัญญาที่ให้ไว้เสมอ",
    en: "Keep my promises.",
    facet: "C3",
    facetName: "Dutifulness",
    factor: "C",
    reverse: false,
  },
  {
    id: 57,
    th: "มักจะต้องบิดเบือนข้อมูลบ่อยๆ",
    en: "Misrepresent the facts.",
    facet: "C3",
    facetName: "Dutifulness",
    factor: "C",
    reverse: true,
  },
  {
    id: 87,
    th: "พูดความจริงเสมอไม่ว่าจะเกิดอะไรขึ้น",
    en: "Tell the truth.",
    facet: "C3",
    facetName: "Dutifulness",
    factor: "C",
    reverse: false,
  },
  {
    id: 117,
    th: "ต้องปฏิบัติตามกฎอย่างเคร่งครัด",
    en: "Stick to the rules.",
    facet: "C3",
    facetName: "Dutifulness",
    factor: "C",
    reverse: false,
  },

  // ── C4: Achievement-Striving ──────────────────────────────
  {
    id: 28,
    th: "ตั้งใจและทำงานหนัก",
    en: "Work hard.",
    facet: "C4",
    facetName: "Achievement-Striving",
    factor: "C",
    reverse: false,
  },
  {
    id: 58,
    th: "ทำงานแค่พอให้ผ่านไปพอแล้ว",
    en: "Do just enough work to get by.",
    facet: "C4",
    facetName: "Achievement-Striving",
    factor: "C",
    reverse: true,
  },
  {
    id: 88,
    th: "เปลี่ยนแผนการให้กลายเป็นการลงมือทำจริง",
    en: "Turn plans into actions.",
    facet: "C4",
    facetName: "Achievement-Striving",
    factor: "C",
    reverse: false,
  },
  {
    id: 118,
    th: "พยายามทำทุกอย่างให้ดีที่สุด",
    en: "Try to do my best at everything.",
    facet: "C4",
    facetName: "Achievement-Striving",
    factor: "C",
    reverse: false,
  },

  // ── C5: Self-Discipline ───────────────────────────────────
  {
    id: 29,
    th: "ทำงานบ้านต่างๆให้เสร็จก่อนทำอย่างอื่น",
    en: "Get chores done right away.",
    facet: "C5",
    facetName: "Self-Discipline",
    factor: "C",
    reverse: false,
  },
  {
    id: 59,
    th: "พบว่าไม่อยากที่จะเริ่มทำงาน",
    en: "Find it difficult to get down to work.",
    facet: "C5",
    facetName: "Self-Discipline",
    factor: "C",
    reverse: true,
  },
  {
    id: 89,
    th: "เริ่มงานในทันทีโดยไม่ผลัดวันประกันพรุ่ง",
    en: "Start tasks right away.",
    facet: "C5",
    facetName: "Self-Discipline",
    factor: "C",
    reverse: false,
  },
  {
    id: 119,
    th: "ทุ่มเทให้กับงานที่รับมอบหมาย",
    en: "Plunge into tasks with all my heart.",
    facet: "C5",
    facetName: "Self-Discipline",
    factor: "C",
    reverse: false,
  },

  // ── C6: Cautiousness ──────────────────────────────────────
  {
    id: 30,
    th: "หลีกเลี่ยงสิ่งที่อาจทำให้เกิดความผิดพลาด",
    en: "Avoid mistakes.",
    facet: "C6",
    facetName: "Cautiousness",
    factor: "C",
    reverse: false,
  },
  {
    id: 60,
    th: "ทำก่อน คิดทีหลัง",
    en: "Act without thinking.",
    facet: "C6",
    facetName: "Cautiousness",
    factor: "C",
    reverse: true,
  },
  {
    id: 90,
    th: "เลือกใช้คำพูดอย่างระวัง",
    en: "Choose my words with care.",
    facet: "C6",
    facetName: "Cautiousness",
    factor: "C",
    reverse: false,
  },
  {
    id: 120,
    th: "ชอบคิดทบทวนสิ่งต่างๆ ก่อนตัดสินใจ",
    en: "Like to think things over before making decisions.",
    facet: "C6",
    facetName: "Cautiousness",
    factor: "C",
    reverse: false,
  },
];

export const ITEMS_PER_PAGE_120 = 10;
export const TOTAL_PAGES_120 = 12; // 120 items ÷ 10 per page

export function getPageItems120(page: number): Item120[] {
  const start = (page - 1) * ITEMS_PER_PAGE_120;
  return items120.slice(start, start + ITEMS_PER_PAGE_120);
}
