/**
 * Translation script: translates IPIP-NEO-120 items to Thai using Gemini
 * and writes lib/items120.ts
 *
 * Usage:
 *   npx tsx scripts/translate-items.ts
 *
 * Requires GEMINI_API_KEY in .env.local
 */

import fs from 'fs'
import path from 'path'
import { rawItems120 } from './raw-items-120'

// Load env
const envPath = path.join(process.cwd(), '.env.local')
if (fs.existsSync(envPath)) {
  const env = fs.readFileSync(envPath, 'utf8')
  for (const line of env.split('\n')) {
    const [key, ...vals] = line.split('=')
    if (key && vals.length) {
      process.env[key.trim()] = vals.join('=').trim()
    }
  }
}

const GEMINI_API_KEY = process.env.GEMINI_API_KEY
if (!GEMINI_API_KEY) {
  console.error('Missing GEMINI_API_KEY in .env.local')
  process.exit(1)
}

const BATCH_SIZE = 20
const MODEL = 'gemini-2.5-flash'

async function translateBatch(sentences: string[]): Promise<string[]> {
  const prompt = `แปลประโยคต่อไปนี้เป็นภาษาไทยที่เป็นธรรมชาติ กระชับ เหมือนบอกเล่าเกี่ยวกับตัวเอง
ไม่ต้องอธิบายหรือเพิ่มคำ ตอบเป็น JSON array ของ string เท่านั้น ไม่ต้องมี markdown fence

${JSON.stringify(sentences)}`

  const res = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models/${MODEL}:generateContent?key=${GEMINI_API_KEY}`,
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [{ role: 'user', parts: [{ text: prompt }] }],
        generationConfig: { temperature: 0.2, maxOutputTokens: 2048 },
      }),
    }
  )

  if (!res.ok) {
    throw new Error(`Gemini API error ${res.status}: ${await res.text()}`)
  }

  const data = await res.json()
  const text = data.candidates?.[0]?.content?.parts?.[0]?.text ?? ''

  // Parse the JSON array from the response
  const cleaned = text.trim().replace(/^```json\s*/i, '').replace(/```\s*$/, '')
  try {
    return JSON.parse(cleaned)
  } catch {
    console.error('Failed to parse batch response:', text)
    throw new Error('Translation parse error')
  }
}

async function main() {
  console.log(`Translating ${rawItems120.length} items in batches of ${BATCH_SIZE}...`)

  const translations: Record<number, string> = {}

  for (let i = 0; i < rawItems120.length; i += BATCH_SIZE) {
    const batch = rawItems120.slice(i, i + BATCH_SIZE)
    console.log(`  Batch ${Math.floor(i / BATCH_SIZE) + 1}/${Math.ceil(rawItems120.length / BATCH_SIZE)} (items ${i + 1}-${Math.min(i + BATCH_SIZE, rawItems120.length)})`)

    const sentences = batch.map(item => item.en)
    const translated = await translateBatch(sentences)

    if (translated.length !== batch.length) {
      throw new Error(`Batch size mismatch: got ${translated.length}, expected ${batch.length}`)
    }

    for (let j = 0; j < batch.length; j++) {
      translations[batch[j].id] = translated[j]
    }

    // Rate limit — wait 1 second between batches
    if (i + BATCH_SIZE < rawItems120.length) {
      await new Promise(resolve => setTimeout(resolve, 1000))
    }
  }

  // Generate lib/items120.ts
  const lines: string[] = [
    '// Auto-generated by scripts/translate-items.ts',
    '// Thai translations of IPIP-NEO-120 items via Gemini',
    '// Review translations before use in production',
    '',
    "import type { FacetCode, Factor } from './scoring120'",
    '',
    'export interface Item120 {',
    '  id: number',
    '  th: string',
    '  en: string',
    '  facet: FacetCode',
    '  facetName: string',
    '  factor: Factor',
    '  reverse: boolean',
    '}',
    '',
    'export const items120: Item120[] = [',
  ]

  for (const item of rawItems120) {
    const th = translations[item.id] ?? item.en
    lines.push(
      `  { id: ${item.id}, th: ${JSON.stringify(th)}, en: ${JSON.stringify(item.en)}, facet: '${item.facet}', facetName: '${item.facetName}', factor: '${item.factor}', reverse: ${item.reverse} },`
    )
  }

  lines.push(']', '')

  const outPath = path.join(process.cwd(), 'lib', 'items120.ts')
  fs.writeFileSync(outPath, lines.join('\n'), 'utf8')
  console.log(`\n✓ Written to ${outPath}`)
  console.log('Review translations before committing.')
}

main().catch(err => {
  console.error(err)
  process.exit(1)
})
